#!/bin/bash
# HP Tourism Portal - Nginx Configuration Script
# Sets up Nginx reverse proxy for the application
set -e

APP_PORT="${HPTOURISM_PORT:-5050}"
NGINX_SITE_NAME="hptourism"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }

NGINX_CONF="/etc/nginx/sites-available/$NGINX_SITE_NAME"

log_info "Creating Nginx configuration..."

cat > "$NGINX_CONF" << EOF
# HP Tourism Portal - Nginx Configuration
# Generated by installer

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name 10.126.117.27 localhost _;

    # Max upload size
    client_max_body_size 25M;

    # Proxy settings
    location / {
        proxy_pass http://127.0.0.1:$APP_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }

    # Static assets caching
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        proxy_pass http://127.0.0.1:$APP_PORT;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # Health check endpoint
    location /api/health {
        proxy_pass http://127.0.0.1:$APP_PORT;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        access_log off;
    }
}
EOF

# Disable default site
rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true

# Enable our site
ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/

# Test configuration
log_info "Testing Nginx configuration..."
nginx -t

# Reload Nginx
log_info "Reloading Nginx..."
systemctl reload nginx

log_success "Nginx configured"
echo "  Site: $NGINX_SITE_NAME"
echo "  Proxy: localhost:$APP_PORT"
echo "  Config: $NGINX_CONF"
