import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { format, formatDistanceToNow } from "date-fns";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import { getStatusLabel } from "@/constants/workflow";
import { fetcher } from "@/lib/queryClient";
import {
  CalendarClock,
  CheckCircle2,
  ClipboardCheck,
  IndianRupee,
  ShieldAlert,
  Undo2,
  Send,
  AlertTriangle,
  XCircle,
  LucideIcon,
} from "lucide-react";

export type TimelineTone = "default" | "primary" | "warning" | "danger";

export type TimelineActor = {
  id: string;
  name: string;
  role: string;
  designation?: string | null;
  district?: string | null;
};

export type TimelineEntry = {
  id: string;
  action: string;
  previousStatus?: string | null;
  newStatus?: string | null;
  feedback?: string | null;
  createdAt?: string | Date | null;
  actor: TimelineActor | null;
};

const ROLE_LABELS: Record<string, string> = {
  property_owner: "Property Owner",
  dealing_assistant: "Dealing Assistant",
  district_tourism_officer: "DTDO",
  district_officer: "District Officer",
  state_officer: "State Officer",
  admin: "Administrator",
  super_admin: "Administrator",
  admin_rc: "RC Admin",
};

export const ACTION_META: Record<
  string,
  {
    icon: LucideIcon;
    label: string;
    description: string;
    tone: TimelineTone;
  }
> = {
  owner_submitted: {
    icon: Send,
    label: "Application submitted",
    description: "Owner submitted the application for verification",
    tone: "primary",
  },
  start_scrutiny: {
    icon: ClipboardCheck,
    label: "Scrutiny started",
    description: "Dealing Assistant picked up the application for verification",
    tone: "primary",
  },
  forwarded_to_dtdo: {
    icon: Send,
    label: "Forwarded to DTDO",
    description: "DA completed scrutiny and shared the remarks",
    tone: "primary",
  },
  reverted_by_da: {
    icon: Undo2,
    label: "Sent back by DA",
    description: "Corrections were requested during document scrutiny",
    tone: "warning",
  },
  inspection_scheduled: {
    icon: CalendarClock,
    label: "Inspection scheduled",
    description: "District officer planned the site inspection",
    tone: "primary",
  },
  inspection_completed: {
    icon: ClipboardCheck,
    label: "Inspection report submitted",
    description: "Inspection findings were recorded",
    tone: "primary",
  },
  inspection_acknowledged: {
    icon: CheckCircle2,
    label: "Inspection acknowledged",
    description: "Owner confirmed the scheduled inspection visit",
    tone: "primary",
  },
  objection_raised: {
    icon: AlertTriangle,
    label: "Objection raised",
    description: "DTDO flagged issues during inspection review",
    tone: "warning",
  },
  dtdo_revert: {
    icon: Undo2,
    label: "Returned by Prescribed Authority",
    description: "Application was reverted for further corrections",
    tone: "warning",
  },
  correction_resubmitted: {
    icon: Send,
    label: "Owner resubmitted",
    description: "Applicant confirmed the corrections and resubmitted",
    tone: "primary",
  },
  dtdo_accept: {
    icon: CheckCircle2,
    label: "Inspection approved",
    description: "DTDO accepted the inspection outcome",
    tone: "primary",
  },
  verified_for_payment: {
    icon: IndianRupee,
    label: "Verified for payment",
    description: "Application cleared for Himkosh payment",
    tone: "primary",
  },
  payment_confirmed: {
    icon: IndianRupee,
    label: "Payment confirmed",
    description: "Payment received via Himkosh",
    tone: "primary",
  },
  certificate_issued: {
    icon: CheckCircle2,
    label: "Certificate issued",
    description: "Registration certificate generated by the department",
    tone: "primary",
  },
  dtdo_reject: {
    icon: XCircle,
    label: "Application rejected",
    description: "Application was rejected at the district level",
    tone: "danger",
  },
  dtdo_correction: {
    icon: ClipboardCheck,
    label: "RC corrected",
    description: "DTDO made corrections to the registration",
    tone: "warning",
  },
  approved: {
    icon: CheckCircle2,
    label: "Approved",
    description: "Application approved",
    tone: "primary",
  },
};

export const formatStatusLabel = (value?: string | null) => {
  if (!value) return null;
  // Use consolidated status mapping from workflow.ts
  return getStatusLabel(value);
};

export const formatActorLabel = (actor: TimelineActor | null) => {
  if (!actor) return "System update";
  const parts = [actor.name];
  const roleLabel = ROLE_LABELS[actor.role] ?? actor.role.replace(/_/g, " ");
  if (roleLabel) {
    parts.push(`· ${roleLabel}`);
  }
  if (actor.district) {
    parts.push(`(${actor.district})`);
  }
  return parts.join(" ");
};

type TimelineResponse = {
  timeline: TimelineEntry[];
};

const toneStyles: Record<TimelineTone, { dot: string; icon: string; badge: string }> = {
  default: {
    dot: "border-muted bg-muted",
    icon: "text-muted-foreground",
    badge: "bg-muted text-muted-foreground",
  },
  primary: {
    dot: "border-primary bg-primary/10",
    icon: "text-primary",
    badge: "bg-primary/10 text-primary",
  },
  warning: {
    dot: "border-amber-500 bg-amber-100 dark:bg-amber-950/40",
    icon: "text-amber-600 dark:text-amber-300",
    badge: "bg-amber-100 text-amber-800 dark:bg-amber-950/40 dark:text-amber-200",
  },
  danger: {
    dot: "border-destructive bg-destructive/10",
    icon: "text-destructive",
    badge: "bg-destructive/10 text-destructive",
  },
} as const;

export function ApplicationTimelineCard({
  applicationId,
  title = "Workflow Timeline",
  description = "Every significant action taken on this application.",
  className,
  preferDtdoEndpoint = false,
}: {
  applicationId?: string | null;
  title?: string;
  description?: string;
  className?: string;
  preferDtdoEndpoint?: boolean;
}) {
  const queryKey = ["/api/applications", applicationId ?? "unknown", "timeline"] as const;
  const { data, isLoading, isError, error } = useQuery<TimelineResponse>({
    queryKey,
    enabled: Boolean(applicationId),
    queryFn: async () => {
      const endpoints = preferDtdoEndpoint
        ? [
          `/api/dtdo/applications/${applicationId}/timeline`,
          `/api/applications/${applicationId}/timeline`,
        ]
        : [
          `/api/applications/${applicationId}/timeline`,
          `/api/dtdo/applications/${applicationId}/timeline`,
        ];

      let lastError: unknown;
      for (const endpoint of endpoints) {
        try {
          return await fetcher<TimelineResponse>(endpoint);
        } catch (err) {
          lastError = err;
          const message = err instanceof Error ? err.message.toLowerCase() : String(err).toLowerCase();
          if (!message.includes("not allowed") && !message.includes("authentication")) {
            break;
          }
        }
      }

      throw lastError instanceof Error ? lastError : new Error(String(lastError));
    },
  });

  const timelineEntries = data?.timeline ?? [];

  const content = useMemo(() => {
    if (!applicationId) {
      return <p className="text-sm text-muted-foreground">Timeline will appear once an application is selected.</p>;
    }

    if (isLoading) {
      return (
        <div className="space-y-4">
          {Array.from({ length: 3 }).map((_, index) => (
            <div key={index} className="space-y-2">
              <Skeleton className="h-4 w-1/3" />
              <Skeleton className="h-3 w-2/3" />
              <Skeleton className="h-14 w-full" />
            </div>
          ))}
        </div>
      );
    }

    if (isError) {
      return (
        <Alert variant="destructive">
          <AlertDescription>{error?.message ?? "Unable to load timeline"}</AlertDescription>
        </Alert>
      );
    }

    if (timelineEntries.length === 0) {
      return <p className="text-sm text-muted-foreground">No workflow updates have been recorded yet.</p>;
    }

    // Helper to format DTDO correction feedback nicely
    const formatFeedback = (entry: TimelineEntry) => {
      if (!entry.feedback) return null;

      // Try to parse JSON for dtdo_correction
      if (entry.action === 'dtdo_correction') {
        try {
          const data = JSON.parse(entry.feedback);
          if (data.type === 'dtdo_correction' && data.changes) {
            return (
              <div className="text-xs space-y-1">
                <div className="font-medium text-amber-700 dark:text-amber-400">
                  Reason: {data.reason}
                </div>
                <div className="grid gap-1">
                  {data.changes.map((change: { field: string; oldValue: string; newValue: string }, i: number) => (
                    <div key={i} className="flex items-center gap-1 text-muted-foreground">
                      <span className="font-medium">{change.field.replace(/([A-Z])/g, ' $1').trim()}:</span>
                      <span className="line-through text-red-500/70">{change.oldValue || 'empty'}</span>
                      <span>→</span>
                      <span className="text-green-600 dark:text-green-400">{change.newValue}</span>
                    </div>
                  ))}
                </div>
              </div>
            );
          }
        } catch {
          // Not JSON, fall through
        }
      }

      // Default: just show the text (truncate if too long)
      const text = entry.feedback.length > 200
        ? entry.feedback.slice(0, 200) + '...'
        : entry.feedback;
      return <span>{text}</span>;
    };

    return (
      <div className="relative pl-4">
        <div className="absolute left-1 top-2 bottom-2 w-px bg-border" />
        <div className="space-y-3">
          {timelineEntries.map((entry) => {
            const meta = ACTION_META[entry.action] ?? {
              icon: ShieldAlert,
              label: entry.action.replace(/_/g, " "),
              description: "Workflow update",
              tone: "default" as TimelineTone,
            };
            const tone = toneStyles[meta.tone];
            const timestamp = entry.createdAt ? new Date(entry.createdAt) : null;
            const previousStatus = formatStatusLabel(entry.previousStatus);
            const newStatus = formatStatusLabel(entry.newStatus);
            // Only show status change if they're actually different
            const hasStatusChange = previousStatus && newStatus && previousStatus !== newStatus;

            return (
              <div key={entry.id} className="relative pl-5">
                <span className={cn("absolute left-0 top-1.5 h-2.5 w-2.5 rounded-full border-2", tone.dot)} />
                <div className="flex flex-col gap-1">
                  {/* Header row - title + timestamp */}
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex items-center gap-1.5 text-sm font-medium">
                      <meta.icon className={cn("h-3.5 w-3.5", tone.icon)} />
                      <span>{meta.label}</span>
                      {hasStatusChange && newStatus !== "Submitted" && (
                        <span className="text-xs font-normal text-muted-foreground">
                          ({previousStatus} → {newStatus})
                        </span>
                      )}
                    </div>
                    {timestamp && (
                      <div className="text-[10px] text-muted-foreground text-right shrink-0 leading-tight">
                        <div>{format(timestamp, "MMM d, h:mm a")}</div>
                        <div className="opacity-70">{formatDistanceToNow(timestamp, { addSuffix: true })}</div>
                      </div>
                    )}
                  </div>

                  {/* Actor - compact */}
                  <p className="text-[11px] text-muted-foreground">{formatActorLabel(entry.actor)}</p>

                  {/* Feedback/Remarks - formatted */}
                  {entry.feedback && (
                    <div className="rounded border bg-muted/30 px-2 py-1.5 text-xs text-muted-foreground">
                      {formatFeedback(entry)}
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    );
  }, [applicationId, isLoading, isError, error, timelineEntries]);

  return (
    <Card className={className}>
      <CardHeader>
        <div className="flex items-center gap-2">
          <CalendarClock className="h-5 w-5 text-primary" />
          <CardTitle>{title}</CardTitle>
        </div>
        {description && <CardDescription>{description}</CardDescription>}
      </CardHeader>
      <CardContent>{content}</CardContent>
    </Card>
  );
}
